### ISSUE TITLE
Feature: Add all of an item

### ISSUE THREAD

**Issue by neocryptek** [neotron/WoW-BulkMail#1]
It would be nice to be able to shift-alt-click an item in your bags and have the addon add all of that same item to the queue (like alt click does with a single item).

I find myself often moving lots of stacks of a single item between characters often enough that alt clicking on every item is annoying, but the exact different items/characters change enough that it doesn't make sense to create a rule for every combination when it comes up.

Currently alt-click adds a single item into the send queue.
https://github.com/neotron/WoW-BulkMail/blob/0de2d44b26ea60f1b1e86e8df410503e057cce52/BulkMail.lua#L699-L700

The proposal would add all of that same item to the send queue, by finding what item id was clicked on, then searching all bags for that same item id, and adding each bag position where it was found to the send queue just like alt-click does.

Example:
Bag with 5 stacks of 200 "Thick Paleo Steak"
alt-click on one stack: one stack of 200 steak is added to the send queue
shift-alt-click on one stack: all stacks of 200 steak is added to the send queue (that are not already in the queue/locked)

Thanks!

**Comment by neotron** [comment]
This is a good idea. I could have used it on many occasions.

**Comment by neotron** [comment]
This is added in the latest release.

**Comment by neotron** [comment]
Moved it to Alt + left click (alt + right click is single) since Ctrl causes the item split dialog to pop up.

**Comment by neocryptek** [comment]
This is awesome! Works great for me.

Only thing I noticed is maybe the localization strings need to be updated? I'm seeing some errors around the new description strings:

```
1x AceLocale-3.0-6: BulkMail: Missing entry for 'Alt-Left Click item to bulk add/remove.'
[string "@BulkMail2\BulkMail.lua"]:1430: in function `ShowSendQueueGUI'
[string "@BulkMail2\BulkMail.lua"]:797: in function `?'
[string "@BulkMail2\Libs\AceHook-3.0\AceHook-3.0-8.lua"]:90: in function <...ceBulkMail2\Libs\AceHook-3.0\AceHook-3.0.lua:87>
```

```
1x AceLocale-3.0-6: BulkMail: Missing entry for 'Alt-Right Click item to add/remove.'
[string "@BulkMail2\BulkMail.lua"]:1429: in function `ShowSendQueueGUI'
[string "@BulkMail2\BulkMail.lua"]:797: in function `?'
[string "@BulkMail2\Libs\AceHook-3.0\AceHook-3.0-8.lua"]:90: in function <...ceBulkMail2\Libs\AceHook-3.0\AceHook-3.0.lua:87>
```

```
1x AceLocale-3.0-6: BulkMail: Missing entry for 'Item Send Queue'
[string "@BulkMail2\BulkMail.lua"]:1367: in function `ShowSendQueueGUI'
[string "@BulkMail2\BulkMail.lua"]:797: in function `?'
[string "@BulkMail2\Libs\AceHook-3.0\AceHook-3.0-8.lua"]:90: in function <...ceBulkMail2\Libs\AceHook-3.0\AceHook-3.0.lua:87>
```

I'm using enUS client so I don't notice any functional problems, but other languages might?

Thanks so much!

**Comment by neotron** [comment]
Fixed these - I had the "debug locale" flag flipped so it was turned on in "release" build and off in my local build.
