### ISSUE TITLE
Broken since Dragonflight Pre-patch

### ISSUE THREAD

**Issue by Kainie85** [neotron/WoW-BulkMail#25]
1x Interface/AddOns/BulkMail2/BulkMail.lua:717: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:210: in function <Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/BulkMail2/BulkMail.lua"]:717: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

**Comment by tinlar** [comment]
In 10.0 the ContainerFrameItemButton_OnModifiedClick and ContainerFrame_Update have been replaced with the ContainerFrameItemButtonMixin.  That's all that needs to be updated.

**Comment by TreizeEU** [comment]
I tried to edit my BulkMail.lua file (lines 717, 719, 763 and 784?) by replacing "ContainerFrameItemButton_OnModifiedClick" and "ContainerFrame_Update" with "ContainerFrameItemButtonMixin", but that didn't seem to fix it.

**Comment by tinlar** [comment]
> I tried to edit my BulkMail.lua file (lines 717, 719, 763 and 784?) by replacing "ContainerFrameItemButton_OnModifiedClick" and "ContainerFrame_Update" with "ContainerFrameItemButtonMixin", but that didn't seem to fix it.

Sorry, I was providing that informaiton to the project owner.  He'll know what I'm talking about.  A mixin is a class that contains methods for use by other classes without having to be the parent class of those other classes.  So it's a little more complex than just changing the call; but should be a simple fix when he gets to it.  

For now you can safely comment out ContainerFrameItemButton_OnModifiedClick and ContainerFrame_Update securehooks.  There will be some quarky things but the addon will mostly work.

**Comment by neotron** [comment]
I'll take a look - haven't fired up 10.x yet.

**Comment by Braymire** [comment]
> > I tried to edit my BulkMail.lua file (lines 717, 719, 763 and 784?) by replacing "ContainerFrameItemButton_OnModifiedClick" and "ContainerFrame_Update" with "ContainerFrameItemButtonMixin", but that didn't seem to fix it.
> 
> Sorry, I was providing that informaiton to the project owner. He'll know what I'm talking about. A mixin is a class that contains methods for use by other classes without having to be the parent class of those other classes. So it's a little more complex than just changing the call; but should be a simple fix when he gets to it.
> 
> For now you can safely comment out ContainerFrameItemButton_OnModifiedClick and ContainerFrame_Update securehooks. There will be some quarky things but the addon will mostly work.

so new to editing/messing around with addon code stuff how comment using Notepad ++ only have block comment and single line comment been kind of relying on Bulkmail to auto mail stuff to characters would like to use it :) least till Neotron gets a update done (take your time no hurry) not trying to rush anyone

**Comment by tinlar** [comment]
> 

You comment it out in LUA by placing two dashes in front of the line --
Notepad++ is a fine tool that will easily allow you to do that.

**Comment by Braymire** [comment]
Broken again lol

**Comment by tinlar** [comment]
There is another submission for 10.0.2 update that further affected this addon.  I posted some poor solutions in there that will get it back up and running for now.

**Comment by neotron** [comment]
Working on fixing this at the moment.

**Comment by neotron** [comment]
Should be fixed.

**Comment by flo187dev** [comment]
Thanks!
