### ISSUE TITLE
broken after Prepatch part 2 

### ISSUE THREAD

**Issue by Braymire** [neotron/WoW-BulkMail#27]
the prepatch part 2 broke Bulkmail again the earlier fixes no longer work

**Comment by tinlar** [comment]
I'm not a project developer and lack the skills of it; I'm more of a "hack it back into working and wait for better men to fix it right" kind of guy.  That being said ...

Assuming you are getting this...
``
1x BulkMail2/BulkMail.lua:551: Usage: GetItemClassInfo(itemClassID)
[string "=[C]"]: in function `GetItemClassInfo'
[string "@BulkMail2/BulkMail.lua"]:551: in function <BulkMail2/BulkMail.lua:507>
[string "=[C]"]: ?
[string "@BagSync/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ceBagSync/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@BagSync/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@BagSync/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ceBagSync/libs/AceAddon-3.0/AceAddon-3.0.lua:611>``

Comment out lines 551 to 561 and paste this after it 

    if GetItemClassInfo(17) then
        obsoletes = newHash(
                5, true,  -- reagent
                6, true,  -- projectile
                11, true,  -- quiver
                12, true,  -- quest item
                13, true,  -- key
                10, true,  -- Money
                14,  true -- Permanent
      )

It'll hobble along until "better men" get to it

**Comment by tinlar** [comment]
There are also three function calls
  GetContainerItemInfo
  GetContainerItemLink
  GetContainerNumSlots 

These appear about 40 times throughout the code and each one will need to have C_Container. added to the start of them such that they appear as 
  C_Container.GetContainerItemInfo
  C_Container.GetContainerItemLink
  C_Container.GetContainerNumSlots 

It really is getting hacky enough that you should probably just live without it until the author publishes an update.

**Comment by neotron** [comment]
I'm working on fixing it for 10.0. there's quite a bit of changes.

**Comment by neotron** [comment]
Should be fixed now.
