### ISSUE TITLE
Can't auto send catch-up gear token from the Forbidden Reach

### ISSUE THREAD

**Issue by B88000005** [neotron/WoW-BulkMail#33]
Can't auto send something like [Primalist Plate Helm](https://www.wowhead.com/ptr/item=203611/primalist-plate-helm)

**Comment by B88000005** [comment]
`Use: Create a soulbound item for your class.` matchs the multiFind(..., ITEM_SOULBOUND, ...) since `soulbound` is in the tooltip. Therefore, the addon thinks the item is soulbound and auto skip the item.

**Comment by neotron** [comment]
Should be fixed in next release.
