### ISSUE TITLE
fix for 9.1

### ISSUE THREAD

**Issue by ilbunilcho** [neotron/WoW-BulkMail#9]
9.1 temporary fix

BulkMail.lua @ 575 line

CHANGE BELOW CODE

`for i = 0, NUM_LE_ITEM_CLASSS-1 do`

TO

`
local NUM_LE_ITEM_CLASSES=_G.NUM_LE_ITEM_CLASSES or _G.NUM_LE_ITEM_CLASSS or 19
`

`
for i = 0, NUM_LE_ITEM_CLASSES-1 do
`

**Comment by neotron** [comment]
This is fixed.
